### ISSUE TITLE
LogKeyModel_predict.ipynb running in an infinite iterations

### ISSUE THREAD

**Issue by raeessrk** [wuyifan18/DeepLog#10]
LogKeyModel_train executed fine but when i tried executing LogKeyModel_predict.ipynb but it is running in an infinite iteration ....

kindly help..

**Comment by raeessrk** [comment]
Thank you @amineebenamor for your concern here are the details
I appended a counter inside both for loop (i.e. for test_normal and test_abnormal ) then I observed that the counter value of test_normal_loader reaches to 800000 and it is still counting and executing...
The execution stuck around first for loop of test_normal_loader and it is not proceeding towards second for loop of test_abnormal_loader

**Comment by LuckyDoggy** [comment]
I have met the same issue. How to deal with it?
