### ISSUE TITLE
The processed dataset

### ISSUE THREAD

**Issue by daphnezmx** [wuyifan18/DeepLog#13]
Hi, I found that the dataset in the ZIP I cloned which is parsed from the raw hdfs log data, is different to what I processed. I processed the same raw log data according to the log template provided by the method called Spell, but I found that the log sequences are different to what is in the "hdfs_train" file and the other three files. And I also found that there are autually 33 log keys rather than 29 log keys. Did you filtered the dataset or not, it confused me these days.

**Comment by errorhandlerst** [comment]
@daphnezmx please use the loglizer for parsing link is here: https://github.com/logpai/logparser/tree/master/logparser/Drain
drain is the most efficient one and after that you should pass HDFS.log_structured.csv to pca which you can find at below link:
https://github.com/logpai/loglizer
and then you can get the file:- data_instances.csv which is the same file as training data of deeplog.
hope these will help you :)
