### ISSUE TITLE
Difference between train data and test_normal data

### ISSUE THREAD

**Issue by riyu94** [wuyifan18/DeepLog#16]
Hi Wufiyan,

I am able to convert structured logs to numbers as your data files and then I feed the train data to LogKeyTrain, model is generated. In the detection stage, the question is what should be the test_normal data. I tried providing a set of logs with similar logkeys but with different blk_id, So the results is not that good. And If I provide test_normal as train_data, I get 100% accuracy, which is obvious.
Could you guide me on how the test_normal data should be.

Great help.
Thank you.

**Comment by riyu94** [comment]
So I assume the blk_id in train and test_normal have to be same, please correct if I am wrong. Though the event sequences can be unique :)

**Comment by riyu94** [comment]
Hi Wufiyan,

Can you help in understanding what is the num_classes in the code used for?

**Comment by wuyifan18** [comment]
@riyu94 num_classes is the number of the log key categories.
