### ISSUE TITLE
Error executing LogKeyModel_train.py

### ISSUE THREAD

**Issue by jpweins** [wuyifan18/DeepLog#19]
(base) jay@pop-os:~/git/DeepLog$ python ./LogKeyModel_train.py 
Number of sessions(hdfs_train): 4855
Number of seqs(hdfs_train): 46575
Traceback (most recent call last):
  File "./LogKeyModel_train.py", line 68, in <module>
    writer = SummaryWriter(log_dir='log/' + log)
  File "/home/jay/.local/lib/python3.6/site-packages/tensorboardX/writer.py", line 254, in __init__
    self._get_file_writer()
  File "/home/jay/.local/lib/python3.6/site-packages/tensorboardX/writer.py", line 310, in _get_file_writer
    self.file_writer = FileWriter(logdir=self.logdir, **self.kwargs)
TypeError: __init__() got an unexpected keyword argument 'log_dir'

**Comment by wuyifan18** [comment]
hi,
You can print the log_dir first.

**Comment by jpweins** [comment]
Hi,

Thanks for the fast response.   I don't understand what your suggesting.
 log/Adam with batch_size=2048;epoch=300 is being passed to SummaryWriter
in main.   Please advise.

Thanks,
Jay

**Comment by wuyifan18** [comment]
Just print(log_dir) to see if the log_dir is correct.

**Comment by jpweins** [comment]
This is what logdir is set to when SummaryWriter is called:    log/Adam
with batch_size=2048;epoch=300
I  looks like logdir isn't set in SummaryWriter.   On line 237 the
following code is executed.
        if not logdir:
            import socket
            from datetime import datetime
            current_time = datetime.now().strftime('%b%d_%H-%M-%S')
            logdir = os.path.join(
                'runs', current_time + '_' + socket.gethostname() + comment)
        self.logdir = logdir

This is what logdir is set to:  runs/May27_23-15-24_pop-os

**Comment by wuyifan18** [comment]
@jpweins Using the newest code which I have updated.

**Comment by jpweins** [comment]
Thanks!!😁
