### ISSUE TITLE
python version

### ISSUE THREAD

**Issue by zhangch-fnst** [wuyifan18/DeepLog#2]
can you share the python version you are using in the project ? python2 or python3 ?
Actually,i am using python3.5 to run the project  in centos6. 
But there are some problems.

**Comment by zhangch-fnst** [comment]
Python 3.5 + CentOS7 =>OK (gcc 4.8.5,glibc 2.17)
Python 3.5 + CentOS6 =>NG
Because CentOS6's gcc and glibc is too old.Cannot support c++11 grammer.

**Comment by wuyifan18** [comment]
hello,
  I'm sorry to have just seen the comments. I use python 3.6. I have uploaded the requirements.txt.

**Comment by zhangch-fnst** [comment]
Thank you for your answer.It is ok now in Python 3.5 + CentOS7.  
I also want to confirm that this code implements the deeplog's [Log Key Anomaly Detection Model] algorithm.But [Parameter Value Anomaly Detection Model] algorithm is not yet implemented.
Is it right?

**Comment by wuyifan18** [comment]
Yes.
