### ISSUE TITLE
Case of single log message in a process.

### ISSUE THREAD

**Issue by sandeepvvn** [wuyifan18/DeepLog#20]
When the data has sequences of length less than a typical window size of 3. The sequences are determined as anomalies, though the sequences are already present in training data.
Making the window size less than 3 doesn't make sense for syslog data. But some process have 1 ,2 or 3 logs over time , they are been taken as anomalies by the lstm.

How can we handle these sequences and not generate more false positives

**Comment by wuyifan18** [comment]
Do you mean the sequences like 5 22 in hdfs_test_abnormal?

**Comment by sandeepvvn** [comment]
lets think i train "5 22" sequence and put it in normal . It is still a false positive

**Comment by wuyifan18** [comment]
Why it is a false positive?
