### ISSUE TITLE
multiple block_ids in sorted.log

### ISSUE THREAD

**Issue by psychogyiokostas** [wuyifan18/DeepLog#22]
Hello,

I have noticed that in the raw log file (sorted.log) which you used to generate the txt files with the sessions, there are lines that contain more than 1 block_ids (they range from 2 up to 100).

An example of a template including multiple block_ids is '<*>BLOCK* ask <*> to delete <*>' .

For these lines we cannot know which of the block_ids is the actual id used for the given session and which are "noise" (if we can use this term..)  

How did you tackle this issue?

Did you, for example, delete such lines from your structured file, or wherever applicable, did you assign the given event_id (action described in the line) to the sessions reflected in the multiple block_ids? (in this case the number of the sessions would remain the same, but their lengths would be slightly longer).

I appreciate your time and thank you very much.

**Comment by goldendeng** [comment]
Sorted.log and 200nodes download link failed,can you offer a new ?

**Comment by wuyifan18** [comment]
@goldendeng 
http://people.iiis.tsinghua.edu.cn/~weixu/demobuild.zip
http://people.iiis.tsinghua.edu.cn/~weixu/200nodes.rar

**Comment by goldendeng** [comment]
@wuyifan18  谢谢了

**Comment by psychogyiokostas** [comment]
Since the link is not valid anymore, you can request the dataset from:

https://zenodo.org/record/3227177#.XbqqpJr7RPY

They normally will grand you access
