### ISSUE TITLE
conversion of system log

### ISSUE THREAD

**Issue by djangid** [wuyifan18/DeepLog#23]
How to use my own system logs i am not sure how to convert them in data model
any help would be appreciated

**Comment by amineebenamor** [comment]
You need to parse them, group independent tasks together before.

**Comment by djangid** [comment]
can you explain more please.

**Comment by amineebenamor** [comment]
I let you read the paper which explains how to preprocess data: https://www.cs.utah.edu/~lifeifei/papers/deeplog.pdf
You can use Spell for parsing for instance, as suggested by DeepLog, or other parsers.

**Comment by djangid** [comment]
thanks thats what i was looking for . do you have some example logs which you used system logs which i can download

**Comment by wuyifan18** [comment]
@djangid [Here](https://www.cs.utah.edu/~mind/papers/deeplog_misc.html) is the data.

**Comment by edocorallounibo** [comment]
Hello @wuyifan18,
I'm using DeepLog for my degree thesis and I have some questions to make about the dataset:
1-I enumerate the EventIds using a simple dictionary, associating subsequent uniques with an integer in a simple for loop. Does the numbers corresponding to unique "EventId" have a meaning beside the 1 to 1 correspondence in the dictionary?  

2- When dividing by sessions ( in HDFS logs by block_id)  do i have to group all EventId corresponding to that block_id regardless of the appearence order?
for example in HDFS:
multiple lines coming from "blk_-1608999687919862906" <--- grouped as first session

multiple lines coming from "blk_7503483334202473044" <--- new session

multiple lines coming from "blk_-1608999687919862906" <--- is this a new session or it has to be grouped with the first one?

3-Is the parameter vector encoded in the dataset (hdfs_train)? I don't quite get where (in the code) does these parameters get fed in the NN, as written in Your paper (sec. 2.2, Training stage).

Thanks for your time and your work!
