### ISSUE TITLE
Number of sessions in test data

### ISSUE THREAD

**Issue by yip522364642** [wuyifan18/DeepLog#26]
Thanks for sharing this code firstly. But I have a question about the number of sessions in test data. For my understanding, in both train and test data, each row represents one session or one block. So the number of sessions of hdfs_test_normal / hdfs_test_abnormal are 553365 / 16838 respectively. But after running "LogKeyModel_predict.py", it shows the following output,

`Number of sessions(hdfs_test_normal): 14177
Number of sessions(hdfs_test_abnormal): 4123`

I wander if my understanding is wrong, or the output is given wrong?

I will always be grateful for your or others reply. 
Thank u again.

**Comment by yip522364642** [comment]
hhh I know the reason~~ hv been shown in the code

**Comment by inesani** [comment]
Hi @yip522364642 I am having the same issue here. Can you tell me what I am missing ?

**Comment by yip522364642** [comment]
> Hi @yip522364642 I am having the same issue here. Can you tell me what I am missing ?

If you run the code "set(XXX)", you will get the same result like what i hv mentioned. Try to run "[XXX]", because "set()" is help to delete the same session, and the session size will smaller.

**Comment by wuyifan18** [comment]
@yip522364642 quite right!

**Comment by wuyifan18** [comment]
@yip522364642 quite right!
@inesani I have mentioned the reason in the code.
https://github.com/wuyifan18/DeepLog/blob/a3824218b71b2a3fa0dd04963058f7e0c17a18c3/LogKeyModel_predict.py#L19-L20

**Comment by inesani** [comment]
thanks, that was it :)

**Comment by wuyifan18** [comment]
You are welcome.
