### ISSUE TITLE
DateSet is 404

### ISSUE THREAD

**Issue by Springlee-P** [wuyifan18/DeepLog#28]
Hello，I asked for a data set address(https://iiis.tsinghua.edu.cn/~weixu/sospdata.html), but I returned a 404. Are there any other addresses I can test?

**Comment by wuyifan18** [comment]
@Springlee-P Hi, I have updated the data set address in README.md.
The prefix of the website for hdfs logs is changed to http://people.iiis.tsinghua.edu.cn/~weixu/, you can download the original data from [raw log](http://people.iiis.tsinghua.edu.cn/~weixu/demobuild.zip) and [200nodes](http://people.iiis.tsinghua.edu.cn/~weixu/200nodes.rar).

Yifan Wu

**Comment by Springlee-P** [comment]
OK、Thank you
