### ISSUE TITLE
Question about the reproducible results?

### ISSUE THREAD

**Issue by donglee-afar** [wuyifan18/DeepLog#32]
I notice your repo used the same parameters as the origin paper,but after the experiment , the result  
F1-measure of this repo is only about ~89%, which is not as good as the 96% in the paper.
What's your experiment result @wuyifan18 ?
Thank you!

**Comment by wuyifan18** [comment]
@donglee-afar just look at these codes bellow, you'll get the answer.
https://github.com/wuyifan18/DeepLog/blob/a82c3128849428c252750ec783cb4bd287a396b5/LogKeyModel_predict.py#L19-L22

Yifan Wu

**Comment by donglee-afar** [comment]
Amazing！I haven't noticed there is so many same sessions in the dataset. Thank you, PKU Wu Yifan!
