### ISSUE TITLE
Dataset not found

### ISSUE THREAD

**Issue by yskale** [wuyifan18/DeepLog#37]
The link to download dataset is not working

**Comment by wuyifan18** [comment]
@yskale It seems that the author who put the dataset on her personal homepage has graduated, so his personal homepage cannot be accessed.

**Comment by yskale** [comment]
Thanks @wuyifan18, I am looking for dataset, can you share the URL for it, if you have any.

**Comment by wuyifan18** [comment]
@yskale I just have the HDFS dataset in https://github.com/wuyifan18/DeepLog/tree/master/data.
