### ISSUE TITLE
Raw log data format

### ISSUE THREAD

**Issue by nagsubhadeep** [wuyifan18/DeepLog#38]
Hi,

I am applying DeepLog on the firewall logs. Does the raw log data need to abide by a certain format for log-parsers such as Spell or Drain? 

Thanks,
Deep

**Comment by wuyifan18** [comment]
@nagsubhadeep 
First, you can use any log parser such as Spell or Drain to extract log key (i.e. log template), and then assign an id to every log according to the id of log key. Finally, you can use the sequences of log id to train DeepLog.
