### ISSUE TITLE
Missing License

### ISSUE THREAD

**Issue by theonewolf** [wuyifan18/DeepLog#4]
It would be great to add a license file such as Apache v2.0, MIT, or BSD.  This would make it clear how your code can be used, and is required for other codebases to properly call your code / import / include it.

**Comment by wuyifan18** [comment]
@theonewolf  Thank you for your reminding. I will add a license right now.

**Comment by theonewolf** [comment]
Thanks @wuyifan18!  You've gone MIT which is very favorable to everyone.  It's actually one of my favorite licenses (as well as Apache v2).
