### ISSUE TITLE
Final Trained Model application on test data

### ISSUE THREAD

**Issue by nagsubhadeep** [wuyifan18/DeepLog#40]
Yifan,

I have one question about your final model. Apart from seeing the precision, recall, and F measure, where can I actually get the predicted results of the anomalies by applying the trained model on the target dataset? In a nutshell, I would want to see which logs from the test data are anomalous, and which are not.

Thanks,
Deep

**Comment by wuyifan18** [comment]
Hi Deep,
If the following code is called, an anomaly is found.
https://github.com/wuyifan18/DeepLog/blob/28f8f2bd4d6f7fa8d783951681bf297639f5d522/LogKeyModel_predict.py#L89-L91

Yifan

**Comment by nagsubhadeep** [comment]
Thanks Yifan.
