### ISSUE TITLE
Training Sequence Size

### ISSUE THREAD

**Issue by nagsubhadeep** [wuyifan18/DeepLog#47]
Yifan,

Is there a limit to the length of the training data log sequence? Can I have a training data sequence as small as the following?

9, 7, 8
8, 9, 7, 8, 4, 7
9, 7, 6, 9, 2
.
.
.
.
7, 8, 9, 5, 8

or a training data sequence as large as the following?

6, 8, 5, 9, 2, 9, ...... 1024 sequences
9, 8, 4, 7,
6, 1, 5, 6, 2, 9, ...... 1004 sequences
.
.
.
6, 10, 5, 9, 3, 9, ...... 1059 sequences

In the latter case, I see that deeplog is misclassifying the sequence in most cases. 

Do you know whether the number of sequences has anything to do with the classification results?

Thanks,
Deep

**Comment by wuyifan18** [comment]
Hi Deep,
the window size, i.e., the number of sequences is a parameter, you can adjust it to achieve the best performance.

**Comment by nagsubhadeep** [comment]
Thanks Yifan
