### ISSUE TITLE
Converting text to numbers

### ISSUE THREAD

**Issue by Xispa33** [wuyifan18/DeepLog#8]
Hi,
Thanks for providing such a complete algorithm, I tested it using everything that was provided, and it worked great !

However, I am trying to use it for a school project (we are recieving logs from an electronic card). The logs that I have are structured (we have already done a preprocessing of the data), but I really struggle to convert the logs to numbers (converting text file to hdfs). Therefore, I cannot train the algorithm using my data. 
I know this question has already been asked before but I really do not understand how it is done, even by reading the paper... Any help is appreciated !

Cheers,

**Comment by liumengkai** [comment]
Hi! @Xispa33 
I found this paper about how we change out log into log key,I hope this will help you.
https://www.cs.utah.edu/~lifeifei/papers/spell.pdf
and I found this :https://github.com/bave/pyspell

**Comment by Xispa33** [comment]
Thanks for the reply @liumengkai ! :)

I managed to parse the log using Spell just yesterday ! After the execution of the algorithm, I am left with 2 csv files : one containing the raw logs converted to structured logs and another identifying the different log events. What should I do with these files ?? (I used https://github.com/logpai/logparser)

In this project, the one thing that I do not understand is where does hdfs_train (located in data/) come from ? Or, how was it obtained? 
I got the raw logs, I parsed them using Spell, now, how can obtain a file that has the same structure as hdfs_train?

**Comment by liumengkai** [comment]
@Xispa33 I will tell you what I know,hope this will help you :-)
The number in the hdfs_train means log key,and that comes from the paper that I mentioned:"https://www.cs.utah.edu/~lifeifei/papers/spell.pdf".
and what can we do to get the log key? I use the algorithm in this github :https://github.com/bave/pyspell, then I could convert my log text into number,but I don't know is this the best way to do.

**Comment by amineebenamor** [comment]
Hello @Xispa33 and @liumengkai,
You should implement the part 4.3.1 of the paper [DeepLog](https://www.cs.utah.edu/~lifeifei/papers/deeplog.pdf) which is missing here. The hdfs_train dataset is preprocessed but I couldn't find this part implemented too.
First, you have to map each log key to a number and afterwards you need to implement the clustering in 4.3.1 to get a task per line (as it's done in hdfs_train).
Let me know if you have more questions, I'm also working on the implementation right now.

**Comment by liumengkai** [comment]
@amineebenamor THX!
Now I know why the length of eachline is different,
I should read the paper more times :-)

**Comment by amineebenamor** [comment]
Hello again @liumengkai @Xispa33 ,
My last message was part of a more general approach which can be applied to any logs.
For HDFS, session window preprocessing was done to generate this train file: we group log entries based on their block id "blk_*" (each line corresponds to a group of log entries, which is called log sequences). For more information concerning this preprocessing, have a look at the paper [Tools and Benchmarks for Automated Log Parsing](https://arxiv.org/pdf/1811.03509.pdf)

**Comment by starovph** [comment]
@amineebenamor Do you have an idea on how one would similarly group ZooKeeper logs for preprocessing? There isn't a similar concept of a "block", unless I'm mistaken.

**Comment by amineebenamor** [comment]
The log format for Zookeeper is:
<Date> <Time> - <Level>  \[<Node>:<Component>@<Id>\] - <Content>
Therefore, you should group the logs corresponding to the same value of [<Node>:<Component>@<Id].

**Comment by starovph** [comment]
Awesome, thanks!

**Comment by raeessrk** [comment]
hello @amineebenamor 
Can you please elaborate on how you got the numerical log key sequence(hdfs_train),
I have parsed the file HDFS.log using Spell and now I have HDFS structured file and template but I am still not clear with the idea of generating numerical log key sequence(i.e. hdfs_train) from that...
Thank you @amineebenamor

**Comment by amineebenamor** [comment]
Hello @raeessrk ,
You just need to match each unique event ID with a number, it's an algorithmic problem that can be solved using a dictionary.

**Comment by raeessrk** [comment]
Thank you @amineebenamor

**Comment by seedjack** [comment]
Hello @amineebenamor @liumengkai ,
I have a question, why the length of eachline is different? If the sliding window size is fixed, the length of eachline should be fixed too.

**Comment by wuyifan18** [comment]
@seedjack , because the length of each line is different, so the length which is smaller than the sliding window size should be filled to the same as sliding window size.
